version: '3.1'

volumes:
  pg-data:
  
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_storage
      POSTGRES_HOST: localhost
    ports:
      - '55432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
